<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHug0lx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHug0lx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHug0lx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHug0lx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHug0lx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHug0lx',
    'container.build_id' => '11639821',
    'container.build_time' => 1700723617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHug0lx');
