<?php

namespace ContainerAHug0lx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0XUrgOZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0XUrgOZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0XUrgOZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'task' => ['privates', '.errored..service_locator.0XUrgOZ.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.0XUrgOZ": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'task' => 'App\\Entity\\Task',
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'validator' => '?',
        ]);
    }
}
