<?php

namespace ContainerAHug0lx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VT9Hz6AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vT9Hz6A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vT9Hz6A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskTree' => ['privates', 'App\\Service\\TasksTree', 'getTasksTreeService', true],
        ], [
            'taskTree' => 'App\\Service\\TasksTree',
        ]);
    }
}
