<?php

namespace ContainerAHug0lx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OCWbZV5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oCWbZV5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oCWbZV5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\StartController::index' => ['privates', '.service_locator.Id0YGQF', 'get_ServiceLocator_Id0YGQFService', true],
            'App\\Controller\\StartController::process' => ['privates', '.service_locator.Id0YGQF', 'get_ServiceLocator_Id0YGQFService', true],
            'App\\Controller\\TaskApiController::changeStatus' => ['privates', '.service_locator.i6A27CL', 'get_ServiceLocator_I6A27CLService', true],
            'App\\Controller\\TaskApiController::delete' => ['privates', '.service_locator.B76IeGe', 'get_ServiceLocator_B76IeGeService', true],
            'App\\Controller\\TaskApiController::description' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController::edit' => ['privates', '.service_locator.0XUrgOZ', 'get_ServiceLocator_0XUrgOZService', true],
            'App\\Controller\\TaskApiController::index' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController::new' => ['privates', '.service_locator.gxkSA7l', 'get_ServiceLocator_GxkSA7lService', true],
            'App\\Controller\\TaskApiController::priority' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController::sortBy' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController::status' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController::taksTree' => ['privates', '.service_locator.vT9Hz6A', 'get_ServiceLocator_VT9Hz6AService', true],
            'App\\Controller\\TaskApiController::title' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.SMj1Mmo', 'get_ServiceLocator_SMj1MmoService', true],
            'App\\Controller\\TaskController::edit' => ['privates', '.service_locator.SMj1Mmo', 'get_ServiceLocator_SMj1MmoService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TaskController::show' => ['privates', '.service_locator.v9K.Cxu', 'get_ServiceLocator_V9K_CxuService', true],
            'App\\Controller\\TaskController::sortBy' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\StartController:index' => ['privates', '.service_locator.Id0YGQF', 'get_ServiceLocator_Id0YGQFService', true],
            'App\\Controller\\StartController:process' => ['privates', '.service_locator.Id0YGQF', 'get_ServiceLocator_Id0YGQFService', true],
            'App\\Controller\\TaskApiController:changeStatus' => ['privates', '.service_locator.i6A27CL', 'get_ServiceLocator_I6A27CLService', true],
            'App\\Controller\\TaskApiController:delete' => ['privates', '.service_locator.B76IeGe', 'get_ServiceLocator_B76IeGeService', true],
            'App\\Controller\\TaskApiController:description' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController:edit' => ['privates', '.service_locator.0XUrgOZ', 'get_ServiceLocator_0XUrgOZService', true],
            'App\\Controller\\TaskApiController:index' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController:new' => ['privates', '.service_locator.gxkSA7l', 'get_ServiceLocator_GxkSA7lService', true],
            'App\\Controller\\TaskApiController:priority' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController:sortBy' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController:status' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskApiController:taksTree' => ['privates', '.service_locator.vT9Hz6A', 'get_ServiceLocator_VT9Hz6AService', true],
            'App\\Controller\\TaskApiController:title' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.SMj1Mmo', 'get_ServiceLocator_SMj1MmoService', true],
            'App\\Controller\\TaskController:edit' => ['privates', '.service_locator.SMj1Mmo', 'get_ServiceLocator_SMj1MmoService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'App\\Controller\\TaskController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TaskController:show' => ['privates', '.service_locator.v9K.Cxu', 'get_ServiceLocator_V9K_CxuService', true],
            'App\\Controller\\TaskController:sortBy' => ['privates', '.service_locator.MW5AobQ', 'get_ServiceLocator_MW5AobQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\StartController::index' => '?',
            'App\\Controller\\StartController::process' => '?',
            'App\\Controller\\TaskApiController::changeStatus' => '?',
            'App\\Controller\\TaskApiController::delete' => '?',
            'App\\Controller\\TaskApiController::description' => '?',
            'App\\Controller\\TaskApiController::edit' => '?',
            'App\\Controller\\TaskApiController::index' => '?',
            'App\\Controller\\TaskApiController::new' => '?',
            'App\\Controller\\TaskApiController::priority' => '?',
            'App\\Controller\\TaskApiController::sortBy' => '?',
            'App\\Controller\\TaskApiController::status' => '?',
            'App\\Controller\\TaskApiController::taksTree' => '?',
            'App\\Controller\\TaskApiController::title' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::edit' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::new' => '?',
            'App\\Controller\\TaskController::show' => '?',
            'App\\Controller\\TaskController::sortBy' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\StartController:index' => '?',
            'App\\Controller\\StartController:process' => '?',
            'App\\Controller\\TaskApiController:changeStatus' => '?',
            'App\\Controller\\TaskApiController:delete' => '?',
            'App\\Controller\\TaskApiController:description' => '?',
            'App\\Controller\\TaskApiController:edit' => '?',
            'App\\Controller\\TaskApiController:index' => '?',
            'App\\Controller\\TaskApiController:new' => '?',
            'App\\Controller\\TaskApiController:priority' => '?',
            'App\\Controller\\TaskApiController:sortBy' => '?',
            'App\\Controller\\TaskApiController:status' => '?',
            'App\\Controller\\TaskApiController:taksTree' => '?',
            'App\\Controller\\TaskApiController:title' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:edit' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:new' => '?',
            'App\\Controller\\TaskController:show' => '?',
            'App\\Controller\\TaskController:sortBy' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
