<?php

namespace ContainerAHug0lx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V9K_CxuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v9K.Cxu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v9K.Cxu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.v9K.Cxu.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.v9K.Cxu": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'tree' => ['privates', 'App\\Service\\TasksTree', 'getTasksTreeService', true],
        ], [
            'task' => 'App\\Entity\\Task',
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'tree' => 'App\\Service\\TasksTree',
        ]);
    }
}
